[tool.poetry]
name = "scoring-credit"
version = "0.1.0"
description = "TP1 MLOps - Du prototype au modele servi"
authors = ["Libas"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
fastapi = "^0.115"
uvicorn = "^0.30"
pydantic = "^2.9"
joblib = "^1.4"
redis = "^5.0"
prometheus-client = "^0.20"
scikit-learn = "^1.5"  # À ajouter
pandas = "<3"
mlflow = "^3.15.2"
dvc = "^3.67.1"
evidently = "<0.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"